// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/tarrencev/starknet-indexer/ent/predicate"
	"github.com/tarrencev/starknet-indexer/ent/transaction"
	"github.com/tarrencev/starknet-indexer/ent/transactionreceipt"
)

// TransactionReceiptQuery is the builder for querying TransactionReceipt entities.
type TransactionReceiptQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.TransactionReceipt
	// eager-loading edges.
	withTransaction *TransactionQuery
	withFKs         bool
	modifiers       []func(*sql.Selector)
	loadTotal       []func(context.Context, []*TransactionReceipt) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TransactionReceiptQuery builder.
func (trq *TransactionReceiptQuery) Where(ps ...predicate.TransactionReceipt) *TransactionReceiptQuery {
	trq.predicates = append(trq.predicates, ps...)
	return trq
}

// Limit adds a limit step to the query.
func (trq *TransactionReceiptQuery) Limit(limit int) *TransactionReceiptQuery {
	trq.limit = &limit
	return trq
}

// Offset adds an offset step to the query.
func (trq *TransactionReceiptQuery) Offset(offset int) *TransactionReceiptQuery {
	trq.offset = &offset
	return trq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (trq *TransactionReceiptQuery) Unique(unique bool) *TransactionReceiptQuery {
	trq.unique = &unique
	return trq
}

// Order adds an order step to the query.
func (trq *TransactionReceiptQuery) Order(o ...OrderFunc) *TransactionReceiptQuery {
	trq.order = append(trq.order, o...)
	return trq
}

// QueryTransaction chains the current query on the "transaction" edge.
func (trq *TransactionReceiptQuery) QueryTransaction() *TransactionQuery {
	query := &TransactionQuery{config: trq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := trq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := trq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(transactionreceipt.Table, transactionreceipt.FieldID, selector),
			sqlgraph.To(transaction.Table, transaction.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, transactionreceipt.TransactionTable, transactionreceipt.TransactionColumn),
		)
		fromU = sqlgraph.SetNeighbors(trq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TransactionReceipt entity from the query.
// Returns a *NotFoundError when no TransactionReceipt was found.
func (trq *TransactionReceiptQuery) First(ctx context.Context) (*TransactionReceipt, error) {
	nodes, err := trq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{transactionreceipt.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (trq *TransactionReceiptQuery) FirstX(ctx context.Context) *TransactionReceipt {
	node, err := trq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TransactionReceipt ID from the query.
// Returns a *NotFoundError when no TransactionReceipt ID was found.
func (trq *TransactionReceiptQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = trq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{transactionreceipt.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (trq *TransactionReceiptQuery) FirstIDX(ctx context.Context) string {
	id, err := trq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TransactionReceipt entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TransactionReceipt entity is found.
// Returns a *NotFoundError when no TransactionReceipt entities are found.
func (trq *TransactionReceiptQuery) Only(ctx context.Context) (*TransactionReceipt, error) {
	nodes, err := trq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{transactionreceipt.Label}
	default:
		return nil, &NotSingularError{transactionreceipt.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (trq *TransactionReceiptQuery) OnlyX(ctx context.Context) *TransactionReceipt {
	node, err := trq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TransactionReceipt ID in the query.
// Returns a *NotSingularError when more than one TransactionReceipt ID is found.
// Returns a *NotFoundError when no entities are found.
func (trq *TransactionReceiptQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = trq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{transactionreceipt.Label}
	default:
		err = &NotSingularError{transactionreceipt.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (trq *TransactionReceiptQuery) OnlyIDX(ctx context.Context) string {
	id, err := trq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TransactionReceipts.
func (trq *TransactionReceiptQuery) All(ctx context.Context) ([]*TransactionReceipt, error) {
	if err := trq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return trq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (trq *TransactionReceiptQuery) AllX(ctx context.Context) []*TransactionReceipt {
	nodes, err := trq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TransactionReceipt IDs.
func (trq *TransactionReceiptQuery) IDs(ctx context.Context) ([]string, error) {
	var ids []string
	if err := trq.Select(transactionreceipt.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (trq *TransactionReceiptQuery) IDsX(ctx context.Context) []string {
	ids, err := trq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (trq *TransactionReceiptQuery) Count(ctx context.Context) (int, error) {
	if err := trq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return trq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (trq *TransactionReceiptQuery) CountX(ctx context.Context) int {
	count, err := trq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (trq *TransactionReceiptQuery) Exist(ctx context.Context) (bool, error) {
	if err := trq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return trq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (trq *TransactionReceiptQuery) ExistX(ctx context.Context) bool {
	exist, err := trq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TransactionReceiptQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (trq *TransactionReceiptQuery) Clone() *TransactionReceiptQuery {
	if trq == nil {
		return nil
	}
	return &TransactionReceiptQuery{
		config:          trq.config,
		limit:           trq.limit,
		offset:          trq.offset,
		order:           append([]OrderFunc{}, trq.order...),
		predicates:      append([]predicate.TransactionReceipt{}, trq.predicates...),
		withTransaction: trq.withTransaction.Clone(),
		// clone intermediate query.
		sql:    trq.sql.Clone(),
		path:   trq.path,
		unique: trq.unique,
	}
}

// WithTransaction tells the query-builder to eager-load the nodes that are connected to
// the "transaction" edge. The optional arguments are used to configure the query builder of the edge.
func (trq *TransactionReceiptQuery) WithTransaction(opts ...func(*TransactionQuery)) *TransactionReceiptQuery {
	query := &TransactionQuery{config: trq.config}
	for _, opt := range opts {
		opt(query)
	}
	trq.withTransaction = query
	return trq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TransactionHash string `json:"transaction_hash,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TransactionReceipt.Query().
//		GroupBy(transactionreceipt.FieldTransactionHash).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (trq *TransactionReceiptQuery) GroupBy(field string, fields ...string) *TransactionReceiptGroupBy {
	grbuild := &TransactionReceiptGroupBy{config: trq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := trq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return trq.sqlQuery(ctx), nil
	}
	grbuild.label = transactionreceipt.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TransactionHash string `json:"transaction_hash,omitempty"`
//	}
//
//	client.TransactionReceipt.Query().
//		Select(transactionreceipt.FieldTransactionHash).
//		Scan(ctx, &v)
//
func (trq *TransactionReceiptQuery) Select(fields ...string) *TransactionReceiptSelect {
	trq.fields = append(trq.fields, fields...)
	selbuild := &TransactionReceiptSelect{TransactionReceiptQuery: trq}
	selbuild.label = transactionreceipt.Label
	selbuild.flds, selbuild.scan = &trq.fields, selbuild.Scan
	return selbuild
}

func (trq *TransactionReceiptQuery) prepareQuery(ctx context.Context) error {
	for _, f := range trq.fields {
		if !transactionreceipt.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if trq.path != nil {
		prev, err := trq.path(ctx)
		if err != nil {
			return err
		}
		trq.sql = prev
	}
	return nil
}

func (trq *TransactionReceiptQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TransactionReceipt, error) {
	var (
		nodes       = []*TransactionReceipt{}
		withFKs     = trq.withFKs
		_spec       = trq.querySpec()
		loadedTypes = [1]bool{
			trq.withTransaction != nil,
		}
	)
	if trq.withTransaction != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, transactionreceipt.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*TransactionReceipt).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &TransactionReceipt{config: trq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(trq.modifiers) > 0 {
		_spec.Modifiers = trq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, trq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := trq.withTransaction; query != nil {
		ids := make([]string, 0, len(nodes))
		nodeids := make(map[string][]*TransactionReceipt)
		for i := range nodes {
			if nodes[i].transaction_receipts == nil {
				continue
			}
			fk := *nodes[i].transaction_receipts
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(transaction.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "transaction_receipts" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Transaction = n
			}
		}
	}

	for i := range trq.loadTotal {
		if err := trq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (trq *TransactionReceiptQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := trq.querySpec()
	if len(trq.modifiers) > 0 {
		_spec.Modifiers = trq.modifiers
	}
	_spec.Node.Columns = trq.fields
	if len(trq.fields) > 0 {
		_spec.Unique = trq.unique != nil && *trq.unique
	}
	return sqlgraph.CountNodes(ctx, trq.driver, _spec)
}

func (trq *TransactionReceiptQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := trq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (trq *TransactionReceiptQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   transactionreceipt.Table,
			Columns: transactionreceipt.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: transactionreceipt.FieldID,
			},
		},
		From:   trq.sql,
		Unique: true,
	}
	if unique := trq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := trq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transactionreceipt.FieldID)
		for i := range fields {
			if fields[i] != transactionreceipt.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := trq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := trq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := trq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := trq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (trq *TransactionReceiptQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(trq.driver.Dialect())
	t1 := builder.Table(transactionreceipt.Table)
	columns := trq.fields
	if len(columns) == 0 {
		columns = transactionreceipt.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if trq.sql != nil {
		selector = trq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if trq.unique != nil && *trq.unique {
		selector.Distinct()
	}
	for _, p := range trq.predicates {
		p(selector)
	}
	for _, p := range trq.order {
		p(selector)
	}
	if offset := trq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := trq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TransactionReceiptGroupBy is the group-by builder for TransactionReceipt entities.
type TransactionReceiptGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (trgb *TransactionReceiptGroupBy) Aggregate(fns ...AggregateFunc) *TransactionReceiptGroupBy {
	trgb.fns = append(trgb.fns, fns...)
	return trgb
}

// Scan applies the group-by query and scans the result into the given value.
func (trgb *TransactionReceiptGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := trgb.path(ctx)
	if err != nil {
		return err
	}
	trgb.sql = query
	return trgb.sqlScan(ctx, v)
}

func (trgb *TransactionReceiptGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range trgb.fields {
		if !transactionreceipt.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := trgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := trgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (trgb *TransactionReceiptGroupBy) sqlQuery() *sql.Selector {
	selector := trgb.sql.Select()
	aggregation := make([]string, 0, len(trgb.fns))
	for _, fn := range trgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(trgb.fields)+len(trgb.fns))
		for _, f := range trgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(trgb.fields...)...)
}

// TransactionReceiptSelect is the builder for selecting fields of TransactionReceipt entities.
type TransactionReceiptSelect struct {
	*TransactionReceiptQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (trs *TransactionReceiptSelect) Scan(ctx context.Context, v interface{}) error {
	if err := trs.prepareQuery(ctx); err != nil {
		return err
	}
	trs.sql = trs.TransactionReceiptQuery.sqlQuery(ctx)
	return trs.sqlScan(ctx, v)
}

func (trs *TransactionReceiptSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := trs.sql.Query()
	if err := trs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
