// Code generated by entc, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/tarrencev/starknet-indexer/ent/block"
	"github.com/tarrencev/starknet-indexer/ent/schema"
	"github.com/tarrencev/starknet-indexer/ent/transaction"
	"github.com/tarrencev/starknet-indexer/ent/transactionreceipt"
)

// TransactionReceipt is the model entity for the TransactionReceipt schema.
type TransactionReceipt struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// TransactionIndex holds the value of the "transaction_index" field.
	TransactionIndex int32 `json:"transaction_index,omitempty"`
	// TransactionHash holds the value of the "transaction_hash" field.
	TransactionHash string `json:"transaction_hash,omitempty"`
	// L1ToL2ConsumedMessage holds the value of the "l1_to_l2_consumed_message" field.
	L1ToL2ConsumedMessage schema.L1ToL2ConsumedMessage `json:"l1_to_l2_consumed_message,omitempty"`
	// ExecutionResources holds the value of the "execution_resources" field.
	ExecutionResources schema.ExecutionResources `json:"execution_resources,omitempty"`
	// Events holds the value of the "events" field.
	Events json.RawMessage `json:"events,omitempty"`
	// L2ToL1Messages holds the value of the "l2_to_l1_messages" field.
	L2ToL1Messages json.RawMessage `json:"l2_to_l1_messages,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TransactionReceiptQuery when eager-loading is set.
	Edges                      TransactionReceiptEdges `json:"edges"`
	block_transaction_receipts *string
	transaction_receipts       *string
}

// TransactionReceiptEdges holds the relations/edges for other nodes in the graph.
type TransactionReceiptEdges struct {
	// Block holds the value of the block edge.
	Block *Block `json:"block,omitempty"`
	// Transaction holds the value of the transaction edge.
	Transaction *Transaction `json:"transaction,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	// totalCount holds the count of the edges above.
	totalCount [2]*int
}

// BlockOrErr returns the Block value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TransactionReceiptEdges) BlockOrErr() (*Block, error) {
	if e.loadedTypes[0] {
		if e.Block == nil {
			// The edge block was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: block.Label}
		}
		return e.Block, nil
	}
	return nil, &NotLoadedError{edge: "block"}
}

// TransactionOrErr returns the Transaction value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TransactionReceiptEdges) TransactionOrErr() (*Transaction, error) {
	if e.loadedTypes[1] {
		if e.Transaction == nil {
			// The edge transaction was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: transaction.Label}
		}
		return e.Transaction, nil
	}
	return nil, &NotLoadedError{edge: "transaction"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TransactionReceipt) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case transactionreceipt.FieldL1ToL2ConsumedMessage, transactionreceipt.FieldExecutionResources, transactionreceipt.FieldEvents, transactionreceipt.FieldL2ToL1Messages:
			values[i] = new([]byte)
		case transactionreceipt.FieldTransactionIndex:
			values[i] = new(sql.NullInt64)
		case transactionreceipt.FieldID, transactionreceipt.FieldTransactionHash:
			values[i] = new(sql.NullString)
		case transactionreceipt.ForeignKeys[0]: // block_transaction_receipts
			values[i] = new(sql.NullString)
		case transactionreceipt.ForeignKeys[1]: // transaction_receipts
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type TransactionReceipt", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TransactionReceipt fields.
func (tr *TransactionReceipt) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case transactionreceipt.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				tr.ID = value.String
			}
		case transactionreceipt.FieldTransactionIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field transaction_index", values[i])
			} else if value.Valid {
				tr.TransactionIndex = int32(value.Int64)
			}
		case transactionreceipt.FieldTransactionHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field transaction_hash", values[i])
			} else if value.Valid {
				tr.TransactionHash = value.String
			}
		case transactionreceipt.FieldL1ToL2ConsumedMessage:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field l1_to_l2_consumed_message", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &tr.L1ToL2ConsumedMessage); err != nil {
					return fmt.Errorf("unmarshal field l1_to_l2_consumed_message: %w", err)
				}
			}
		case transactionreceipt.FieldExecutionResources:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field execution_resources", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &tr.ExecutionResources); err != nil {
					return fmt.Errorf("unmarshal field execution_resources: %w", err)
				}
			}
		case transactionreceipt.FieldEvents:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field events", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &tr.Events); err != nil {
					return fmt.Errorf("unmarshal field events: %w", err)
				}
			}
		case transactionreceipt.FieldL2ToL1Messages:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field l2_to_l1_messages", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &tr.L2ToL1Messages); err != nil {
					return fmt.Errorf("unmarshal field l2_to_l1_messages: %w", err)
				}
			}
		case transactionreceipt.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field block_transaction_receipts", values[i])
			} else if value.Valid {
				tr.block_transaction_receipts = new(string)
				*tr.block_transaction_receipts = value.String
			}
		case transactionreceipt.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field transaction_receipts", values[i])
			} else if value.Valid {
				tr.transaction_receipts = new(string)
				*tr.transaction_receipts = value.String
			}
		}
	}
	return nil
}

// QueryBlock queries the "block" edge of the TransactionReceipt entity.
func (tr *TransactionReceipt) QueryBlock() *BlockQuery {
	return (&TransactionReceiptClient{config: tr.config}).QueryBlock(tr)
}

// QueryTransaction queries the "transaction" edge of the TransactionReceipt entity.
func (tr *TransactionReceipt) QueryTransaction() *TransactionQuery {
	return (&TransactionReceiptClient{config: tr.config}).QueryTransaction(tr)
}

// Update returns a builder for updating this TransactionReceipt.
// Note that you need to call TransactionReceipt.Unwrap() before calling this method if this TransactionReceipt
// was returned from a transaction, and the transaction was committed or rolled back.
func (tr *TransactionReceipt) Update() *TransactionReceiptUpdateOne {
	return (&TransactionReceiptClient{config: tr.config}).UpdateOne(tr)
}

// Unwrap unwraps the TransactionReceipt entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (tr *TransactionReceipt) Unwrap() *TransactionReceipt {
	tx, ok := tr.config.driver.(*txDriver)
	if !ok {
		panic("ent: TransactionReceipt is not a transactional entity")
	}
	tr.config.driver = tx.drv
	return tr
}

// String implements the fmt.Stringer.
func (tr *TransactionReceipt) String() string {
	var builder strings.Builder
	builder.WriteString("TransactionReceipt(")
	builder.WriteString(fmt.Sprintf("id=%v", tr.ID))
	builder.WriteString(", transaction_index=")
	builder.WriteString(fmt.Sprintf("%v", tr.TransactionIndex))
	builder.WriteString(", transaction_hash=")
	builder.WriteString(tr.TransactionHash)
	builder.WriteString(", l1_to_l2_consumed_message=")
	builder.WriteString(fmt.Sprintf("%v", tr.L1ToL2ConsumedMessage))
	builder.WriteString(", execution_resources=")
	builder.WriteString(fmt.Sprintf("%v", tr.ExecutionResources))
	builder.WriteString(", events=")
	builder.WriteString(fmt.Sprintf("%v", tr.Events))
	builder.WriteString(", l2_to_l1_messages=")
	builder.WriteString(fmt.Sprintf("%v", tr.L2ToL1Messages))
	builder.WriteByte(')')
	return builder.String()
}

// TransactionReceipts is a parsable slice of TransactionReceipt.
type TransactionReceipts []*TransactionReceipt

func (tr TransactionReceipts) config(cfg config) {
	for _i := range tr {
		tr[_i].config = cfg
	}
}
